### ISSUE TITLE
any interest in collaborating?

### ISSUE THREAD

**Issue by adamfk** [TediCreations/HSM#2]
Hi!

I'm the author of [StateSmith](https://github.com/StateSmith/StateSmith) and a fellow embedded C99 state machine enthusiast!

I recently came across your project and saw that we have similar goals: 
* suitable for baremetal
* HSM
* no use of malloc

Any interest in [collaborating](https://github.com/StateSmith/StateSmith/wiki/About)? There's not a lot of State Machine enthusiasts like us out there. It would be awesome if we could combine our efforts.

Adam :)

**Comment by eliaskanelis** [comment]
I have just seen StateSmith and it is awesome! Of course.
The code here is written 5-6 years ago and I recently started updating the repo and have plans to rewrite parts of the code and test beyond 3 levels of nesting.

I would love to work with you! :)

Ilias

**Comment by adamfk** [comment]
We can chat over at https://github.com/StateSmith/StateSmith/discussions or https://discord.com/invite/rNxNGQXWsU . Either one is fine. 

Looking forward to working together :)

**Comment by eliaskanelis** [comment]
In the end it is all about free time. Not enough for me this period of my life.

**Comment by adamfk** [comment]
No worries! Life gets busy.
